---

- name: Check for homebrew.
  stat:
    path: /usr/local/bin/brew
  register: stat_homebrew
  ignore_errors: True

- name: Install package.
  homebrew:
    name: git
    state: present
  when: stat_homebrew.stat.executable == True
