---
# Install and zsh package, set up zshrc.

- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - packages

- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - packages

- include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'

# Setup zshrc/prompt

- name: Set as default shell
  user:
    name: "{{ item.key }}"
    shell: /bin/zsh
  loop: "{{ __users__ | default({}) | dict2items }}"
  when: >-
    (ansible_os_family == 'RedHat' or ansible_os_family == 'Debian') and
    ("zsh_default_shell" in item.value and item.value.zsh_default_shell)

- name: Generate ~/.zshrc.
  template:
    mode: 0644
    src: zshrc.j2
    owner: "{{ user_shell.key }}"
    dest: "~{{ user_shell.key }}/.zshrc"
  loop: "{{ __users__ | default({}) | dict2items }}"
  loop_control:
    loop_var: user_shell
  vars:
    zsh_username: "{{ user_shell.key }}"
    user_options: "{{ user_shell.value }}"

- name: Check for .zfunctions directory.
  file:
    state: directory
    mode: 0755
    owner: "{{ item.key }}"
    dest: "~{{ item.key }}/.zfunctions"
  loop: "{{ __users__ | default({}) | dict2items }}"

- name: Upload zfunctions files
  copy:
      src: "./{{ item.value.zsh_zfunctions_directory }}/"
      dest: "~{{ item.key }}/.zfunctions/"
      owner: "{{ item.key }}"
      directory_mode: yes
      force: yes
      mode: 0755
  loop: "{{ __users__ | default({}) | dict2items }}"
  when: >-
    "zsh_zfunctions_directory" in item.value

- name: Download zsh prompt file.
  get_url:
    mode: 0744
    owner: "{{ item.key }}"
    url: "{{ item.value.zsh_prompt_download_url | default(zsh_default_prompt_download_url) }}"
    checksum: "{{ item.value.zsh_prompt_download_md5 | default(zsh_default_prompt_download_md5) }}"
    dest: "~{{ item.key }}/.zfunctions/prompt_{{ item.value.zsh_prompt_name | default(zsh_default_prompt_name) }}_setup"
  loop: "{{ __users__ | default({}) | dict2items }}"
  when: >-
    "zsh_prompt_install" in item.value and item.value.zsh_prompt_install

- name: Download zsh prompt additional file.
  get_url:
    mode: 0744
    owner: "{{ item.key }}"
    url: "{{ item.value.zsh_prompt_additional_url }}"
    checksum: "{{ item.value.zsh_prompt_additional_md5 | default(omit) }}"
    dest: "~{{ item.key }}/.zfunctions/{{ zsh_prompt_additional_url | basename | replace('.zsh', '') }}"
  loop: "{{ __users__ | default({}) | dict2items }}"
  when: >-
    "zsh_prompt_install" in item.value and item.value.zsh_prompt_install and
    "zsh_prompt_additional_url" in item.value and item.value.zsh_prompt_additional_url

- name: Download zsh additional file if install default prompt.
  get_url:
    mode: 0744
    owner: "{{ item.key }}"
    url: "{{ zsh_default_prompt_additional_url }}"
    checksum: "{{ zsh_default_prompt_additional_md5 | default(omit) }}"
    dest: "~{{ item.key }}/.zfunctions/{{ zsh_default_prompt_additional_url | basename | replace('.zsh', '') }}"
  loop: "{{ __users__ | default({}) | dict2items }}"
  when: >-
      "zsh_prompt_install" in item.value and item.value.zsh_prompt_install and not
      "zsh_prompt_name" in item.value
